services:
  - type: web
    name: aura-live-backend
    runtime: node
    rootDir: server
    region: ohio
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_umiWgz9I2CXP@ep-odd-glade-axbcygiw-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_ACCESS_SECRET
        value: auralive_super_secure_access_secret_key_2026_production_v2_9981247
      - key: JWT_REFRESH_SECRET
        value: auralive_super_secure_refresh_secret_key_2026_production_v2_1823901
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: AGORA_APP_ID
        value: 2be3d44a55ed429ba2cb13ee348a8364
      - key: AGORA_APP_CERTIFICATE
        value: 6d737e61f25d4d3396e1a30a2faba769
      - key: ADMIN_INITIAL_EMAIL
        value: admin@auralive.io
      - key: ADMIN_INITIAL_PASSWORD
        value: AuraLiveAdmin2026!Secure
